### ISSUE TITLE
Line resolution isn't working on table-like structures

### ISSUE THREAD

**Issue by devendrapal5755** [mindee/doctr#841] opened 2022-03-07 08:45 UTC
### 🚀 The feature

I have extract word by line , because when i am using block and then line part faced issues some word will not sequence wise. 

### Motivation, pitch

word in proper sequence order require

**Comment by fg-mindee** [comment] 2022-03-07 12:05
Hi @devendrapal5755 :wave: 

I'm sorry, I'm not sure I understand your problem here. Do you mean that the words are not ordered correctly in lines & blocks in your predictions?

Either way, could you share a minimal snippet to reproduce this behaviour (and the document/page you performed the inference on) please? This would allow us to reproduce this and investigate :pray:

**Comment by fg-mindee** [comment] 2022-03-10 10:53
Any update @devendrapal5755 ? :)

**Comment by devendrapal5755** [comment] 2022-03-10 11:01
LEASE DEED Rs- 5,50,500- Rs- 8,25,000- 
Premum Stamp Duty Paid On 
Lease Rent Rs- 32,550- Stamp Duty: Rs- 41,250- 
THIS STAMP PAPER ATTACHED WITH LEASE DEED FOR RESIDENTIAL BUILT UP HOUSE/FLAT NO- 376 First Floor), SECTOR-OMICRON 1A, AREA-31 Se Mtr VIDE ALLOTMENT NO. BHS1088303 ALLOTTED BY GREATER NOIDA INDUSTRIAL DEVELOPMENT AUTHORITY, DISTT, GAUTAM BUDH NAGAR. (U.P.) ALLOTTEE NAME IS SH. RAJV KUMAR GUPTA S/O LATE SH. INDRA PAL GUPTA R/O 170 B, SHARAMIK 
KUNJ, SECTOR- 66, NOIDA G.B. NAGAR (U.P.). 
![page0](https://user-images.githubusercontent.com/58802107/157648717-b5cf3198-9a7e-4a03-a8e6-4a9c7278b11b.jpg)

**Comment by devendrapal5755** [comment] 2022-03-10 11:03
you can see model consider block - The lees deed and Rs-5,50,000/- same as premium stamp duty paid now .
Actually i want same as it in image .

**Comment by frgfm** [comment] 2022-07-20 09:32
Hi @devendrapal5755 @NGStaph :wave: 

Sorry about the late reply! Would you mind sharing your input doc/image and elaborating on the expected vs actual result please? :pray:

**Comment by NGStaph** [comment] 2022-07-21 09:17
on second thought.. i might be getting an error due to warp within '00093726.png' of the [FUNSD dataset](https://guillaumejaume.github.io/FUNSD/download/). the order of words that docTR outputs on a deskewed version of the image is unexpected/incorrect maybe related to #537 ?

Actual Order: `'Date: Soplembe r 21, 1/6', 'Sample No. 6030', 'Type of Cigarette', '85 mm Filter', '50 lbs.', 'Batch Size', 'Dr. A. W. Spears', 'Original Request Made By.', 'Sample Specifications Written By.', 'on September 21, 1976', 'W. E. Routh'`.....

**Comment by frgfm** [comment] 2022-07-26 11:57
Hi @NGStaph,

I'm sorry but I don't think I get the difference between what you want and what you currently have :sweat_smile: 
So I'll share relevant information hoping that will help you:
- as you can see in https://github.com/mindee/doctr/blob/main/doctr/datasets/funsd.py#L95, only unknown characters are removed from the loaded data of FUNSD
- the convention selected by the dataset creator/owner is up to them, we have tried to keep from altering that
- in docTR, our predictors and document builders consider word as being uninterrupted sequences of characters (no white space)

Feel free to give more specifics about your problem if that doesn't help :) Also, if the topic is starting to different from the orginal issue description, please consider opening another dedicated issue :pray:

**Comment by kuraga** [comment] 2023-01-25 17:57
@frgfm , @charlesmindee , is line resolution provided? We have an example from  README and the image from https://github.com/mindee/doctr/pull/537#issuecomment-950655246.

![image](https://user-images.githubusercontent.com/1063219/214643656-7d89da64-4412-4ca6-bbb6-aafb09579761.png)
![image](https://user-images.githubusercontent.com/1063219/214643716-33fcf595-2543-454f-9742-00dd885a4a00.png)

These worlds are totally different!

And I don't get a line via README's code. WDIDW?

Thanks!

**Comment by frgfm** [comment] 2023-04-29 09:35
Hi @kuraga :wave:

Circling back to this, here are some answers:
- the README snippet does not use line resolution (feel free to enable it)
- on the other picture, as you pointed it out, the spatial density of lines is quite different. The only robust method I can see is to use both spatial and semantic information (we verify our spatial understanding by checking whether the 2-part sentence makes sense). Since line resolution in docTR has been using heuristics so far, it's difficult to accommodate all distributions indeed :sweat_smile: 

I suggest not trying to resolve lines and doing it on your own if you have a very specific spatial distribution :ok_hand: 

Cheers!

**Comment by kuraga** [comment] 2023-04-30 14:32
@frgfm , thanks!

> the README snippet does not use line resolution (feel free to enable it)

How do I enable it?

**Comment by frgfm** [comment] 2023-05-28 11:36
Hey @kuraga,

This is a constructor arg of the `DocumentBuilder` (https://github.com/mindee/doctr/blob/main/doctr/models/builder.py#L32-L33) that you can pass as kwargs to the `ocr_predictor` https://mindee.github.io/doctr/latest/modules/models.html#doctr.models.ocr_predictor

I hope this helps!

**Comment by kuraga** [comment] 2023-05-28 12:37
@frgfm , thanks!

P.S.

> the README snippet does not use line resolution (feel free to enable it)

> This is a constructor arg of the DocumentBuilder (https://github.com/mindee/doctr/blob/main/doctr/models/builder.py#L32-L33) that you can pass as kwargs to the ocr_predictor https://mindee.github.io/doctr/latest/modules/models.html#doctr.models.ocr_predictor

https://github.com/mindee/doctr/blob/1bf12a3ec73ddb463420d4243133b2d423a602d3/doctr/models/builder.py#L32-L33

Hm, it's enabled by default...

**Comment by frgfm** [comment] 2023-05-28 13:48
@kuraga it depends on your version of the library, but yes it's enabled by default on the dev version currently ;)
I suggest passing that as a kwarg if you aren't using the latest dev version !

**Comment by felixdittrich92** [comment] 2023-09-17 12:24
Closing this because looks like it's solved :)
Otherwise feel free to answer on this thread for re-opening

**Closed by felixdittrich92** 2023-09-17 12:24 UTC
Labels: module: models, awaiting response, topic: table comprehension
