### ISSUE TITLE
ERROR:uvicorn.error:Exception in ASGI application

### ISSUE THREAD

**Issue by kiko0217** [mindee/doctr#900] opened 2022-04-27 05:07 UTC
### Bug description

when run docker-compose up -d build in the docker logs get ERROR:uvicorn.error:Exception in ASGI application when open localhost:8002/redoc. i use windows.

![image](https://user-images.githubusercontent.com/69133007/165443274-0fe51cdf-efdb-487f-8045-5151a344f354.png)

### Code snippet to reproduce the bug

localhost:8002/redoc

### Error traceback

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "/app/./app/main.py", line 26, in add_process_time_header
    response = await call_next(request)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 161, in openapi
    return JSONResponse(self.openapi())
  File "/app/./app/main.py", line 36, in custom_openapi
    openapi_schema = get_openapi(
  File "/usr/local/lib/python3.8/site-packages/fastapi/openapi/utils.py", line 410, in get_openapi
    return jsonable_encoder(OpenAPI(**output), by_alias=True, exclude_none=True)  # type: ignore
  File "pydantic/main.py", line 406, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 4 validation errors for OpenAPI
components -> schemas -> DetectionOut -> properties -> box -> items
  value is not a valid dict (type=type_error.dict)
components -> schemas -> DetectionOut -> $ref
  field required (type=value_error.missing)
components -> schemas -> OCROut -> properties -> box -> items
  value is not a valid dict (type=type_error.dict)
components -> schemas -> OCROut -> $ref
  field required (type=value_error.missing)
ERROR:uvicorn.error:Exception in ASGI application

### Environment

DocTR version: 0.6.0a0
TensorFlow version: 2.6.3
PyTorch version: N/A (torchvision N/A)
OpenCV version: 4.5.5
OS: Debian GNU/Linux 11 (bullseye)
Python version: 3.8.12
Is CUDA available (TensorFlow): No
Is CUDA available (PyTorch): N/A
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

### Deep Learning backend

Python 3.8.12 (default, Sep 28 2021, 19:14:48)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from doctr.file_utils import is_tf_available, is_torch_available
ailable()}")
print(f"is_torch_available: {is_torch_available()}")2022-04-27 04:59:10.662193: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared 
object file: No such file or directory
2022-04-27 04:59:10.662279: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] 
Ignore above cudart dlerror if you do not have a GPU set up on your machine.     
>>> 
>>> print(f"is_tf_available: {is_tf_available()}")
is_tf_available: True
>>> print(f"is_torch_available: {is_torch_available()}")
is_torch_available: False
>>> from doctr.file_utils import is_tf_available, is_torch_available
>>> print(f"is_tf_available: {is_tf_available()}")
is_tf_available: True

**Comment by charlesmindee** [comment] 2022-04-28 08:05
Hi @kiko0217, thanks for the report. Can you give the exact code snippet to reproduce the bug (all the commands you executed which led to the screenshot you attached) ? Thanks!

**Comment by kiko0217** [comment] 2022-04-29 17:10
> Hi @kiko0217, thanks for the report. Can you give the exact code snippet to reproduce the bug (all the commands you executed which led to the screenshot you attached) ? Thanks!

I'm just run:
> PORT=8002 docker-compose up -d --build
and then run to look logs:
>  docker container logs -f <name-container>
then in my browser open http://localhost:8002/redoc

**Comment by spielhoelle** [comment] 2022-05-04 15:49
Same problem here. Followed the docker section of the readme to use it as an standalone api endpoint, but opening the http://localhost:8002/redoc page results in the above mentioned error
<img width="1385" alt="Screenshot 2022-05-04 at 22 39 56" src="https://user-images.githubusercontent.com/6317641/166718493-648b0519-adcc-41f7-a10b-dc1221043ee7.png">

**Comment by charlesmindee** [comment] 2022-05-05 13:47
#847 refers to the same bug

**Comment by frgfm** [comment] 2022-05-07 10:32
Hi @kiko0217 👋 

As mentioned by @charlesmindee, this very much looks like a duplicate of #847, let's move all the discussions over there 🙏

**Closed by frgfm** 2022-05-07 10:32 UTC
Labels: type: bug, duplicate, topic: docker, os: windows
