### ISSUE TITLE
Cannot run doctr with Docker

### ISSUE THREAD

**Issue by fharper** [mindee/doctr#479] opened 2021-09-16 20:57 UTC
## 🐛 Bug

I cannot build the doctr Docker image. I get an error (see attached video) when the requirements are being installed.

## To Reproduce

Steps to reproduce the behaviour:

1. Build the Docker image
2.
3. Profit!

## Expected behavior

Being able to use doctr with the Dockerfile provided

## Environment

OS: Mac OSX 11.5.2 on a M1 chip (it shouldn't change anything since the pip install runs inside the container)
Docker: 20.10.8, build 3967b7

https://user-images.githubusercontent.com/1170989/133692402-e949aa2f-6338-4d30-a2df-85accb62ccdb.mp4

d

**Comment by fg-mindee** [comment] 2021-09-17 10:39
Hi @fharper,

Thanks for reporting this!
To make sure I get the root problem correctly here, can you confirm that you are able to install DocTR outside of Docker with the same setup?

While it's true your setup is generally not the limiting factor for OS compatibility via Docker, there are cases, I  have personally experienced, where it's not possible (trying to build an image for an ARM chip while yours isn't). So my guess is that the base installation outside of Docker isn't working because you would need the ARM wheels for all dependencies.

If that's the case, I'll investigate this in #430 shortly!

**Comment by fharper** [comment] 2021-09-17 13:33
You are right, I cannot even install the requirements on my M1 MacBook. I'll create another issue for it as #430 is focussing on arm for low powered devices, while the M1 processor is arm64: AFAIK, it will be two different built, and does not need the same requirements/versions.

**Comment by fg-mindee** [comment] 2021-09-17 14:03
Let's first address #480, I'm rather confident that if it gets fixed, then resolving this issue will be casual :)

**Comment by felixdittrich92** [comment] 2022-09-10 18:24
Hi @fharper can we close this ? :)

**Comment by frgfm** [comment] 2022-09-16 10:09
Closing this as #480 is the root cause :+1:

**Closed by frgfm** 2022-09-16 10:09 UTC
Labels: type: bug, topic: docker, os: mac
