### ISSUE TITLE
Error when installing requirement on a M1 MacBook

### ISSUE THREAD

**Issue by fharper** [mindee/doctr#480] opened 2021-09-17 13:54 UTC
## 🐛 Bug

When I try to install the requirements to run doctr on my M1 MacBook, I get an `ModuleNotFoundError: No module named '_ctypes'`. I installed the additional packages required for macOS users.

https://user-images.githubusercontent.com/1170989/133793566-a8b97c2c-55a7-4129-bd95-a4c6535f9798.mp4

## To Reproduce

1. `pip install -r requirements.txt`

## Expected behavior

No error when installing the packages.

## Environment

DocTR version: N/A
TensorFlow version: N/A
PyTorch version: N/A (torchvision N/A)
OpenCV version: N/A
OS: Mac OSX 11.5.2
Python version: 3.7
Is CUDA available (TensorFlow): N/A
Is CUDA available (PyTorch): N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
How you installed DocTR (`conda`, `pip`, source): I did not, I'm trying to use the code from the repository I cloned

**Comment by fg-mindee** [comment] 2021-09-17 14:02
Thanks for reporting it!
If M1 MacOS users are getting more common, we indeed have to handle this. However if this is correct, it seems the issue is due to numpy rather than DocTR. In order to confirm this, let's try to get numpy to work and then try again on the same setup :) 

@fharper would you mind trying this trick : https://stackoverflow.com/a/65581354 to install numpy?
If this works and that doctr installation can be completed afterwards, I will add a warning note for M1-MacOS users in the installation instructions :ok_hand:

**Comment by fg-mindee** [comment] 2021-09-30 15:54
Thanks for investigating @fharper :pray: 

We'll have to think about a way to counter this, the quick fix of adding constraints on the python version is quite heavy on other OS (or even for MacOS considering most users are not necessarily running M1 chips). Most likely, we'll have to ping the authors of the corresponding libraries to investigate this issue!

**Comment by fharper** [comment] 2021-10-18 13:29
I'm giving it another try, will keep folks up to date.

I'll keep my steps here, but keep in mind it's not final, and may change:
```
brew install bazel
pip install Keras-Preprocessing
./configure
bazel build //tensorflow/tools/pip_package:build_pip_package
./bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
```

**Comment by fg-mindee** [comment] 2021-10-18 14:25
Thanks @fharper :pray: 

Have you followed some tutorials or guidelines from a specific resource? If not, is keras preprocessing required to build TF?

**Comment by fharper** [comment] 2021-12-07 14:40
I didn't have time to try to make it work again. I think I've checked those tutorials, but it wasn't working for me. I'll give it another try as soon as I can.

**Comment by fg-mindee** [comment] 2021-12-07 14:54
Oh yeah, it's more for tracking purposes :+1:
Considering the efforts that people have to put into this to make it work on M1 chips, I wouldn't advise jumping back into this if you're busy!

**Comment by fharper** [comment] 2022-03-16 15:09
Will try, thanks!

**Comment by felixdittrich92** [comment] 2022-09-10 18:22
Hi @fharper can we close this ? :)

**Comment by frgfm** [comment] 2022-09-16 10:08
So PyTorch stable now supports Mac M1 architecture!
However about TensorFlow, it looks like a plugin is needed: https://developer.apple.com/metal/tensorflow-plugin/

**Comment by felixdittrich92** [comment] 2022-09-16 10:29
sounds like a lot of trouble :sweat_smile:

**Comment by frgfm** [comment] 2022-09-21 11:32
For now, we should perhaps update the installation instructions in the README & documentation to close this :+1:

**Comment by felixdittrich92** [comment] 2022-09-25 09:38
I will try to add some information in the docs. Unfortunately i don't have the option to test it.

**Closed** 2022-09-27 10:21 UTC
Labels: type: bug, topic: build, awaiting response, os: mac
