### ISSUE TITLE
Loaded cuDNN version 8400

### ISSUE THREAD

**Issue by skywalkerzhang** [mindee/doctr#912] opened 2022-05-10 06:54 UTC
### Bug description

I try to run the demo with python3.9, cuda 11.3, torch 1.10.0+cu113, cudnn version 82003

How can I solve this problem? Thank you in advance.

### Code snippet to reproduce the bug

```python
from doctr.models import ocr_predictor
from doctr.io import DocumentFile

model = ocr_predictor(pretrained=True, export_as_straight_boxes=True)
# Image
single_img_doc = DocumentFile.from_images("test.png")
result = model(single_img_doc)
print("done")
```

### Error traceback
```
C:\Users\rina\AppData\Local\Programs\Python\Python39\lib\site-packages\weasyprint\fonts.py:215: UserWarning: @font-face not supported: FontConfig cannot load default config file
  warnings.warn(
C:\Users\rina\AppData\Local\Programs\Python\Python39\lib\site-packages\weasyprint\fonts.py:457: UserWarning: Expect ugly output with font-size: 0
  warnings.warn('Expect ugly output with font-size: 0')
C:\Users\rina\AppData\Local\Programs\Python\Python39\lib\site-packages\weasyprint\document.py:35: UserWarning: There are known rendering problems and missing features with cairo < 1.15.4. WeasyPrint may work with older versions, but please read the note about the needed cairo version on the "Install" page of the documentation before reporting bugs. http://weasyprint.readthedocs.io/en/latest/install.html
  warnings.warn(
2022-05-10 13:39:25.033842: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-05-10 13:39:25.461588: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 3969 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 2060, pci bus id: 0000:01:00.0, compute capability: 7.5
DEBUG:tensorflow:Layer lstm will use cuDNN kernels when running on GPU.
DEBUG:tensorflow:Layer lstm will use cuDNN kernels when running on GPU.
DEBUG:tensorflow:Layer lstm will use cuDNN kernels when running on GPU.
DEBUG:tensorflow:Layer lstm_1 will use cuDNN kernels when running on GPU.
DEBUG:tensorflow:Layer lstm_1 will use cuDNN kernels when running on GPU.
DEBUG:tensorflow:Layer lstm_1 will use cuDNN kernels when running on GPU.
2022-05-10 13:39:29.226392: I tensorflow/stream_executor/cuda/cuda_dnn.cc:368] Loaded cuDNN version 8400

Process finished with exit code -1073740791 (0xC0000409)
```

### Environment

python3.9, cuda 11.3, torch 1.10.0+cu113, cudnn version 82003

### Deep Learning backend

both True

**Comment by skywalkerzhang** [comment] 2022-05-10 14:16
> Hi @skywalkerzhang 👋,
> 
> Could you please provide the output from: https://github.com/mindee/doctr/blob/main/scripts/collect_env.py ? If you have both frameworks in the same env installed and want to use PyTorch than you need to set a environment variable : For PT: `export USE_TORCH=1` For TF: `export USE_TF=1`
> 
> Another think is, that we currently not test with a python 3.9 environment so would it be possible that you test it with 3.8 ? :)

DocTR version: 0.5.1
TensorFlow version: 2.8.0
PyTorch version: 1.10.0+cu113 (torchvision 0.11.1+cu113)
OpenCV version: 4.5.4
OS: Microsoft Windows 10 רҵ▒▒
Python version: 3.9.7
Is CUDA available (TensorFlow): Yes
Is CUDA available (PyTorch): Yes
CUDA runtime version: 11.6.124
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin\cudnn_ops_train64_8.dll
Fontconfig error: Cannot load default config file

**Comment by felixdittrich92** [comment] 2022-05-11 06:29
Could you please check your Nvidia driver version ? https://nvidia.custhelp.com/app/answers/detail/a_id/2039/~/how-do-i-determine-which-nvidia-display-driver-version-is-currently-installed

And test if it's work with setting the environment variable `USE_TORCH=1`   ? 
Otherwise i think it is a problem with the combination (Windows, python 3.9 and especially weasyprint) @frgfm 

It is a bit hard for me to debug this without an windows environment so i need your support @skywalkerzhang  :sweat:

**Comment by skywalkerzhang** [comment] 2022-05-13 14:29
Thanks for your suggestion @felixdittrich92 . I tested with `USE_TORCH=1` and it downloads pt files successfully. After that, another error comes up `Fontconfig error: Cannot load default config file`.
Full outputs:
```
C:\Users\rina\AppData\Local\Programs\Python\Python39\lib\site-packages\weasyprint\fonts.py:215: UserWarning: @font-face not supported: FontConfig cannot load default config file
  warnings.warn(
C:\Users\rina\AppData\Local\Programs\Python\Python39\lib\site-packages\weasyprint\fonts.py:457: UserWarning: Expect ugly output with font-size: 0
  warnings.warn('Expect ugly output with font-size: 0')
C:\Users\rina\AppData\Local\Programs\Python\Python39\lib\site-packages\weasyprint\document.py:35: UserWarning: There are known rendering problems and missing features with cairo < 1.15.4. WeasyPrint may work with older versions, but please read the note about the needed cairo version on the "Install" page of the documentation before reporting bugs. http://weasyprint.readthedocs.io/en/latest/install.html
  warnings.warn(
Downloading https://github.com/mindee/doctr/releases/download/v0.3.1/db_resnet50-ac60cadc.pt to C:\Users\rina\.cache\doctr\models\db_resnet50-ac60cadc.pt
101971968it [01:11, 1435110.95it/s]                              
Downloading https://github.com/mindee/doctr/releases/download/v0.3.1/crnn_vgg16_bn-9762b0b0.pt to C:\Users\rina\.cache\doctr\models\crnn_vgg16_bn-9762b0b0.pt
63287296it [01:44, 604988.32it/s]                               
done
Fontconfig error: Cannot load default config file
```

I don't know if is caused by weasyprint. I found this documentation [WeasyPrint DOC](https://doc.courtbouillon.org/weasyprint/latest/first_steps.html#windows) and it says only win11 is supported but I use win10 this moment.

**Comment by frgfm** [comment] 2022-05-16 22:55
Hi all 👋 

The last problem mentioned here is indeed linked to weasyprint, but the issue is reporting a problem about TensorFlow failing at loading cuDNN. So about this current issue, I'd suggest to simply reproduce this with TensorFlow and potentially reinstall this :)

Your error shows that the problem comes from much deeper than docTR, the framework is trying to load GPU-related hardware acceleration libraries and it fails. So this might indicate, as suggested by Felix, that you're gonna need to reinstall cuda!

**Comment by felixdittrich92** [comment] 2022-05-20 07:43
@skywalkerzhang any update or can we close this ? :)

**Closed** 2022-05-23 15:25 UTC
Labels: type: bug, module: models, framework: tensorflow, awaiting response, os: windows
