### ISSUE TITLE
Received incompatible tensor with shape (127,) when attempting to restore variable with shape (124,) and name dense/bias:0.

### ISSUE THREAD

**Issue by suresrikanth101** [mindee/doctr#1405] opened 2023-12-11 13:29 UTC
### Bug description

I tried to finetune recognization with tensorflow framework in my labelled data, when I load weights,Iam getting error like ValueError: Received incompatible tensor with shape (127,) when attempting to restore variable with shape (124,) and name dense/bias:0. But checkpoint, weights.data and weights.index files are stored properly. plz help 

### Code snippet to reproduce the bug

from doctr.models import ocr_predictor, db_resnet50, crnn_vgg16_bn
# Load custom recognition model
reco_model = crnn_vgg16_bn(pretrained=False, pretrained_backbone=False)
reco_model.load_weights(r"C:\Users\SSure\OneDrive - Genzeon Corporation\Desktop\POc\doctr\crnn_vgg16_bn_20231211-180856/weights")
predictor = ocr_predictor(det_arch="linknet_resnet18", reco_arch=reco_model, pretrained=True)

### Error traceback

ValueError: Received incompatible tensor with shape (127,) when attempting to restore variable with shape (124,) and name dense/bias:0.

### Environment

DocTR version: 1.9.0
TensorFlow version: 2.15.0
PyTorch version: 2.1.1+cpu (torchvision 0.16.1+cpu)
OpenCV version: 4.5.4
OS: Could not collect
Python version: 3.10.11
Is CUDA available (TensorFlow): No
Is CUDA available (PyTorch): No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

### Deep Learning backend

is_tf_available: True
is_torch_available: False

**Comment by felixT2K** [comment] 2023-12-11 15:36
Hi @suresrikanth 👋🏼 ,

you missed to specify the vocab the model was trained on :)

See for example:

```
from doctr.models import ocr_predictor, crnn_vgg16_bn
from doctr.datasets import VOCABS

reco_model = crnn_vgg16_bn(pretrained=False, pretrained_backbone=False, vocab=VOCABS["german"])  <--- this
reco_model.load_weights("<path_to_checkpoint>/weights")

predictor = ocr_predictor(det_arch='linknet_resnet18', reco_arch=reco_model, pretrained=True)
```

**Comment by suresrikanth** [comment] 2023-12-12 01:43
Hi @felixT2K,
I was trying to increase my accuracy on handwritten text, so I prepared handwritten labeled data and started finetuning with that data. I was getting error like above. Note: Here I used for english only, in this case no need to place vocab at that place, am I right?

**Comment by felixT2K** [comment] 2023-12-12 07:30
Can you please try the following:

```
reco_model = crnn_vgg16_bn(pretrained=False, pretrained_backbone=False, vocab=VOCABS["french"])
reco_model.load_weights("<path_to_checkpoint>/weights")
```

The problem is that the default from crnn_vgg16_bn is still legacy_french with 124 characters (it was one of the first trained models) but the default in the training script is french with 127 characters

**Comment by suresrikanth** [comment] 2023-12-12 13:55
I tried with vocab=VOCABS["french"] in my reco_model, at the time of detection it won't detect hand written text, before finetuning my model default model detecting handwritten text but at the time of recognization, it fails to recognize doctor notes. So to improve that part I started finetuning on my data. But this time completely fails to detect handwritten text.
<img width="356" alt="Screenshot 2023-12-12 192346" src="https://github.com/mindee/doctr/assets/68548376/edf29f7b-40f2-4dee-b50a-61c6f26ce31d">

**Comment by suresrikanth** [comment] 2023-12-12 14:02
when I use the default code below
model = ocr_predictor(det_arch = 'db_resnet50',    
                      reco_arch = 'crnn_vgg16_bn', 
                      pretrained = True
                     )
doc = DocumentFile.from_images('image_path')
result = model(doc)
# Export the results to JSON
json_response = result.export()
result.show()
detecting like below 
<img width="350" alt="1" src="https://github.com/mindee/doctr/assets/68548376/7360ada2-5dc5-4678-8864-63f8bcdf36e5">

**Comment by felixT2K** [comment] 2023-12-12 14:21
Could you please share the code snippet you used with loading your custom model ? 
changing the recognition model has no impact on the detection model so this looks super weird 😅

**Comment by suresrikanth** [comment] 2023-12-12 14:25
I used below code
reco_model = crnn_vgg16_bn(pretrained=False, pretrained_backbone=False, vocab=VOCABS["french"])
reco_model.load_weights("<path_to_checkpoint>/weights")
predictor = ocr_predictor(det_arch="linknet_resnet18", reco_arch=reco_model, pretrained=True)
doc = DocumentFile.from_images(r'<image path>')
result = predictor(doc)

**Comment by felixT2K** [comment] 2023-12-12 14:28
A now i got it you used 2 different detection models .. in this case you should use `db_resnet50` for detection if the results are better instead of `linknet_resnet18`

**Comment by felixT2K** [comment] 2023-12-12 14:39
So sounds like the issue is fixed on your side ? :)

**Comment by suresrikanth** [comment] 2023-12-13 06:17
Hi @felixT2K,
When I am taking inferences text inside the document detecting properly, but when it comes to recognization it fails, in the json response value is empty space and it also  provided corresponding boundary boxes as well. plz find below screenshot of json response.
<img width="660" alt="2" src="https://github.com/mindee/doctr/assets/68548376/370d4509-6397-4661-bf74-62ebae093c8b">

**Comment by felixT2K** [comment] 2023-12-13 07:32
H @suresrikanth,

This depends on how you have trained the model, have you used `--pretraned` and fine tuned the model or trained it from scratch ?
How many samples are in your dataset ?
Also `crnn_vgg16_bn` is not the optimal choice for handwritten recognition you should use a model which uses attention (transformer) i suggest `parseq` because it is small and really powerful

**Comment by felixT2K** [comment] 2023-12-13 07:33
The ground issue seems to be solved i will covert it to a discussion :)

**Closed as completed** 2023-12-13 07:33 UTC
Labels: type: bug
